server:
  port: 9093
  error:
    include-message: always

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/posts/**
#            filters:
#              - name: CircuitBreaker
#            args:
#              name: SERVICE-NAME
#              fallbackuri: forward:/NameOfTheFallBackForThsiService

eureka:
  client :
    register-with-eureka: true
    fetch-registry : true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost